### ISSUE TITLE
include_loadings causes error

### ISSUE THREAD

**Issue by SlevinKelevraAU** [martinbaumgaertner/hfdshocks#2]
Hi :) First of all, many thanks for your efforts in providing an easy-to-use function to extract the EAMPD shocks, this is greatly appreciated. The following is just FYI.

Currently, your example gives some errors. First, some function input names have changed, e.g. 'range := date_range' or 'loadings := include_loadings' and some others. Second, I get the following error after adjusting and using 'include_loadings=T':  _'vcovHC' is not an exported object from 'namespace:lmtest'_ .

Example I:
_#load package
library(devtools)
devtools::install_github("https://github.com/martinbaumgaertner/hfdshocks.git") 

library(hfdshocks)
ecb_shocks(range=c("2001-12-31","2021-10-13"),crisis_date="2008-09-04",path="data/",
                 reproduce=F,extended=T,extended_release_date="2015-12-03",
                 loadings=T,return_data = "all")_

Example II (after fixing input names):

_ecb_shocks(date_range =c("2001-12-31","2021-10-13"),
           crisis_date="2008-09-04",
           path="~/Downloads",
           reproduce=F,
           extended=T,
           extended_release_date="2015-12-03",
           include_loadings=T,
           return_data="all")_

Cheers,
SK

**Comment by martinbaumgaertner** [comment]
Hey @SlevinKelevraAU ,

thank you for your Report. Seems i missed some checks after refactoring. The current build fixes this :)

**Comment by martinbaumgaertner** [comment]
[Fixed in this release](https://github.com/martinbaumgaertner/hfdshocks/releases/tag/1.0)

**Comment by SlevinKelevraAU** [comment]
Cool, many thanks for your rapid reply and the fix :) Greatly appreciated!
One question for understanding though: If I run _ecb_shocks(path="~/SOMEPATH",date_range =c("2001-12-31","2023-12-31"))_ I should expect to extract factors (target, timing, fg and qe) mirroring the approach of Altavilla (due to your defaults), i.e. the QE factor has a minimum variance before the crisis?

And some follow up questions: I am interested in the QE factor. When executing the command above I do get the QE factor but was wondering as its variation before 2008 compared to the target factor still looks quite high. Or is the QE variance restriction only comparable against the other unconventional factors? In order to call this factor QE one simply sets all values before ~2014/2015 to zero and gets the picture from the Altavilla paper?

Cheers,
SK

**Comment by martinbaumgaertner** [comment]
Hey,
the Authors made a small error in the preprocessing which i fixed in this package. The ecb_shocks function has a parameter 'reproduce' to replicate the original preprocessing. With this parameter the factors should be similar.

![image](https://github.com/user-attachments/assets/9d85ea8f-f765-4001-b555-90b554ae70c5)

![image](https://github.com/user-attachments/assets/9ab02800-a1b7-435d-80f0-c498e990131f)



To your follow up Question:
I must say that i never compared the variation between the surprises. The original justification for the surprise naming is the loading structure.

Yes the values before 2014 are just set to 0.

**Comment by SlevinKelevraAU** [comment]
Cool, thanks for your reply, understood! :)
